server:
    port: 8080
    servlet:
           context-path: /autenticacao

spring:
    profiles:
           active: dev
    datasource:
            url: jdbc:mysql://localhost:3306/acessos
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
    jpa:
            show-sql: true
            database-platform: org.hibernate.dialect.MySQLDialect
            properties:
                  hibernate:
                      format_sql: true

    liquibase:
        change-log: classpath:db/changelog-master.xml
        enabled: true
        default-schema: acessos
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}

security:
      oauth2:
            resource:
                filter-order: 3